from file_extractor import extractor as e

def stop():
    stopwords = ['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves']
    return stopwords


def love_words():
    words = ['adorable',
            'affection',
            'amour',
            'angel',
            'bliss',
            'caring',
            'chocolate',
            'companion',
            'compassion',
            'concern',
            'darling',
            'dear',
            'desire',
            'devotion',
            'endearment',
            'family',
            'fondness',
            'forever',
            'friendship',
            'fun',
            'God',
            'happiness',
            'happy',
            'heart',
            'hugs',
            'husband',
            'infatuation',
            'inspiration',
            'intimacy',
            'joy',
            'kiss',
            'kisses',
            'loyalty',
            'marriage',
            'passion',
            'relationship',
            'romance',
            'sex',
            'sweet',
            'sweetheart',
            'tenderness',
            'trust',
            'warmth',
           'wife']
    return words

def positive():
    poslist = ['abound', 'accessible', 'accolades', 'accomplishment', 'achievement', 'adaptive', 'admiration', 'adorable', 'adoringly', 'adulatory', 'advantages', 'advocates', 'affection', 'affirmative', 'affordably', 'agreeable', 'alluringly', 'amazement', 'ambitiously', 'amiabily', 'amity', 'amusingly', 'appealing', 'appreciates', 'approve', 'aspiration', 'assure', 'astonishing', 'astounding', 'attractive', 'auspicious', 'aver', 'awards', 'awesomeness', 'bargain', 'beautify', 'beckons', 'beneficent', 'benefits', 'best-known', 'better-than-expected', 'bliss', 'bloom', 'bonuses', 'bountiful', 'bravery', 'breathtaking', 'brighter', 'brilliantly', 'cajole', 'capable', 'cashback', 'celebration', 'charismatic', 'chaste', 'cheery', 'chivalrous', 'classic', 'cleanliness', 'clearer', 'cohere', 'comely', 'comfy', 'commodious', 'compatible', 'complements', 'conciliate', 'congenial', 'conscientious', 'consummate', 'convenience', 'convient', 'cooperative', 'cost-effective', 'courageous', 'covenant', 'crisp', 'cute', 'daringly', 'dazzle', 'decency', 'defeat', 'deference', 'delicate', 'delightfully', 'deserving', 'detachable', 'dignified', 'diligently', 'distinguished', 'dominated', 'dreamland', 'dynamic', 'earnestly', 'easier', 'easy-to-use', 'ecenomical', 'ecstatically', 'effectiveness', 'effortless', 'effusiveness', 'elation', 'elevate', 'embolden', 'empower', 'enchantingly', 'endear', 'endorses', 'energy-saving', 'enhancement', 'enjoyed', 'enlightenment', 'enrapture', 'entertain', 'enthralled', 'enthusiastically', 'entranced', 'envious', 'ergonomical', 'euphoria', 'eventful', 'exalted', 'examplary', 'exceedingly', 'excellant', 'excellently', 'excited', 'exciting', 'exhilarate', 'expansive', 'extol', 'exuberant', 'exultingly', 'fabulous', 'fairness', 'fame', 'fancinating', 'fantastically', 'fashionable', 'faster', 'fave', 'favorited', 'feasibly', 'felicitate', 'fervently', 'fidelity', 'finer', 'first-rate', 'flawless', 'flourishing', 'fondness', 'fortitude', 'fortune', 'freedoms', 'friendly', 'fulfillment', 'gaily', 'gaining', 'geekier', 'generous', 'gentlest', 'gladly', 'gleefully', 'glitter', 'glory', 'god-send', 'good', 'gooood', 'gracefully', 'grandeur', 'gratifies', 'great', 'guarantee', 'gusto', 'hallmark', 'hands-down', 'happily', 'hardy', 'harmony', 'hearten', 'heaven', 'hero', 'heros', 'homage', 'honored', 'hot', 'humane', 'humorously', 'ideally', 'illuminate', 'ilu', 'immense', 'impeccable', 'impresses', 'improved', 'incredible', 'indulgent', 'infallibility', 'ingeniously', 'innovation', 'inspiration', 'instructive', 'intelligent', 'intimate', 'intuitive', 'invigorating', 'invulnerable', 'issue-free', 'jovial', 'joyously', 'jubiliant', 'keenness', 'knowledgeable', 'laudably', 'lawfully', 'led', 'liberation', 'likable', 'lionhearted', 'lovably', 'lover', 'low-priced', 'lucid', 'luckiness', 'luster', 'luxuriously', 'magnanimous', 'majestic', 'marveled', 'marvelousness', 'masterpiece', 'mature', 'merciful', 'merrily', 'mesmerized', 'meticulously',  
'miracles', 'modest', 'morality', 'neatest', 'nicest', 'noiseless', 'nourish', 'oasis', 'openness', 'orderly', 'outperformed', 'outsmart', 'ovation', 'overtaking', 'painlessly', 'pamperedness', 'pardon', 'patient', 'peaceable', 'peerless', 'peps', 'perseverance', 'phenomenally', 'playfully', 'pleasing', 'plentiful', 'poeticize', 'polite', 'positive', 'praise', 'precise', 'preferably', 'premier', 'priceless', 'prize', 'prodigiously', 'proficiently', 'progress', 'promise', 'prompt', 'propitiously', 'prospros', 'proven', 'prudence', 'purify', 'quicker', 'rapid', 'raptureously', 'reachable', 'reaffirmation', 'reasoned', 'recomend', 'reconcile', 'rectification', 'redemption', 'reformed', 'refreshing', 'regard', 'rejuvenated', 'reliably', 'remedy', 'renown', 'resilient', 'resourcefulness', 'respite', 'restored', 'revel', 'reverently', 'revolutionary', 'rewarding', 'richness', 'righteousness', 'risk-free', 'rockstars', 'roomy', 'sagely', 'salute', 'satisfies', 'savings', 'seasoned', 'self-respect', 'sensational', 'sensitive', 'sharper', 'shiny', 'simplified', 'sincerely', 'skillfully', 'smarter', 'smiling', 'smoothes', 'sociable', 'solicitously', 'sophisticated', 'sparkle', 'speedy', 'spirited', 'spontaneous', 'stabilize', 'stately', 'steadfast', 'steady', 'stimulating', 'streamlined', 'stronger', 'stupendous', 'stylishly', 'subsidize', 'succeed', 'success', 'sufficed', 'sumptuous', 'superbly', 'supported', 'supremacy', 'surmount', 'sustainability', 'swanky', 'sweetly', 'talented', 'tempt', 'tenacity', 'thank', 'thoughtfulness', 'thrilling', 'thumb-up', 'timely', 'togetherness', 'top-quality', 'toughest', 'treasure', 'triumphant', 'trump', 'trustingly', 'truthfully', 'unabashedly', 'unbound', 'understandable', 'unequivocal', 'unity', 'unquestionably', 'unwavering', 'upheld', 'upliftment', 'user-friendly', 'valuable', 'versatile', 'victory', 'virtuous', 'vouch', 'warmly', 'well-backlit', 'well-connected', 'well-known', 'well-received', 'wellbeing', 'whoooa', 'win', 'winning', 'witty', 'wonderous', 'work', 'worth', 'wow', 'youthful']

    return poslist

def negative():
    neglist = ['abnormal', 'abomination', 'abrasive', 'absent-minded', 'absurdness', 'abysmal', 'accursed', 'accusing', 'ache', 'acrid', 'acrimony', 'addicting', 'admonishment', 'adulterier', 'afflict', 'aggravate', 'aggressiveness', 'aghast', 'agony', 'aimless', 'alienate', 'allege', 'altercation', 'ambush', 'anarchistic', 'angriness', 'annihilation', 'annoying', 'antagonism', 'anti-american', 'anti-social', 'antithetical', 'anxiousness', 'apocalyptic', 'appalled', 'apprehensive', 'arduous', 'arrogantly', 'askance', 'assassin', 'asunder', 'attack', 'audacity', 'autocratic', 'avenge', 'awfully', 'babble', 'backaches', 'backwardness', 'baffle', 'balk', 'banishment', 'barbarity', 'bash', 'bastards', 'beastly', 'beggar', 'belated', 'belittling', 'bemoan', 'bereave', 'beset', 'betrayal', 'bewail', 'bewilderingly', 'biases', 'bigotry', 'bitter', 'blabber', 'bland', 'blasted', 'bleakly', 'blemish', 'blister', 'bloodshed', 'blunder', 'bluring', 'blurt', 'boiling', 'bombastic', 'boredom', 'bothered', 'boycott', 'brash', 'brazen', 'break-up', 'breakup', 'brittle', 'browbeat', 'brusque', 'brutalize', 'bs', 'bugs', 'bull****', 'bully', 'bumped', 'bungle', 'burdensome', 'burns', 'butchery', 'calamitous', 'calumniation', 'cancer', 'capricious', 'carelessness', 'cash-strapped', 'cataclysmal', 'catastrophic', 'cautionary', 'chagrin', 'chastise', 'cheapen', 'cheating', 'chide', 'choke', 'chunky', 'cliched', 'cloud', 'clunky', 'coercive', 'collusion', 'commonplace', 'complained', 'complex', 'compulsive', 'concen', 'concession', 'condemned', 'condescension', 'conflict', 'confounded', 'confuse', 'confusions', 'conservative', 'conspirator', 'contaminate', 'contempt', 'contention', 'contradiction', 'contrived', 'corrosion', 'corrupting', 'costly', 'coward', 'cracks', 'cramped', 'craps', 'crass', 'craziness', 'credulous', 'crept', 'cringes', 'crisis', 'criticize', 'crook', 'crude', 'cruelness', 'crummy', 'crushed', 'cumbersome', 'cursed', 'cutthroat', 'damaged', 'damnably', 'danger', 'darkened', 'daunt', 'dazed', 'deadweight', 'debase', 'debaucher', 'debt', 'decayed', 'deceive', 'deceptive', 'declining', 'defamation', 'defective', 'defiantly', 'defiler', 'defy', 'degrade', 'deign', 'delay', 'delinquent', 'deluge', 'demeaning', 'demonic', 'demoralize', 'denies', 'dented', 'deny', 'deplore', 'depravedly', 'depressingly', 'deride', 'derogatory', 'desiccated', 'despair', 'desperation', 'despoil', 'despondently', 'destains', 'destruction', 'deteriorating', 'detestably', 'detracted', 'detrimental', 'devastatingly', 'devilish', 'deviously', 'diabolically', 'dick', 'died', 'diffidence', 'dimmer', 'dire', 'dirtbags', 'disaccord', 'disaffect', 'disagreeably', 'disallow', 'disappointed', 'disappoints', 'disarm', 'disastrously', 'disbeliever', 'discomfort', 'disconcertingly', 'discontented', 'discord', 'discouragement', 'discoutinous', 'discriminatory', 'disfavor', 'disgruntle', 'disgustful', 'disheartening', 'dishonor', 'disillusionment', 'disingenuously', 'disinterest',
            'disliking', 'dismally', 'dismayingly', 'disobey', 'disorganized', 'disparaging', 'dispiritedly', 'displeased', 'disputable', 'disquietingly', 'disrepute', 'disrespectfully', 'disruptive', 'dissatisfaction', 'dissatisfying', 'dissent', 'dissidence', 'dissolute', 'dissuade', 'distastefully', 'distract', 'distraughtness', 'distrust', 'disturbed', 'divergent', 'dizzingly', 'doggedly', 'donside', 'doubt', 'douchebag', 'downfall', 'downhill', 'drab', 'dragging', 'draining', 'drawbacks', 'dreary', 'drones', 'dropout', 'drunkard', 'dud', 'dump', 'dungeon', 'dwindling', 'effigy', 'egotistical', 'elimination', 'embarrassingly', 'embroilment', 'encroach', 'enervate', 'enmity', 'entangle', 'enviously', 'erode', 'erratic', 'errors', 'evade', 'evils', 'exagerates', 'exasperating', 'exclusion', 'excuses', 'exhausts', 'exorbitantance', 'expired', 'expropriate', 'extermination', 'extravagance', 'extremists', 'facetious', 'fails', 'faithless', 'fallaciously', 'fallout', 'falsify', 'fanatic', 'fanciful', 'farcically', 'fastidiously', 'fatal', 'fatcats', 'fatigued', 'fatuously', 'faze', 'fearsome', 'feign', 'ferociously', 'fevers', 'fiction', 'fiend', 'filthy', 'flabbergast', 'flair', 'flakieness', 'flareup', 'flawed', 'fleer', 'flickering', 'flirt', 'flout', 'foolhardy', 'forbidden', 'forfeit', 'forlorn', 'foul', 'fracture', 'frantically', 'frazzle', 'freakishly', 'frenetic', 'fretful', 'friggin', 'frighteningly', 'frown', 'frustrate', 'frustration', 'fugitive', 'fumes', 'furious', 'fussy', 'futility', 'gainsay', 'galls', 'gasp', 'geezer', 'ghosting', 'gimmick', 'glare', 'glitches', 'glum', 'god-awful', 'graceless', 'grate', 'greedy', 'grieving', 'grind', 'gross', 'groundless', 'grudging', 'grumble', 'grumpy', 'gullible', 'haggard', 'hallucinate', 'hang', 'harass', 'harbors', 'hardball', 'hardliner', 'harmed', 'harried', 'hassle', 'hasty', 'hatefulness', 'hatred', 'havoc', 'haze', 'heartbreaker', 'heavy-handed', 'heckles', 'hefty', 'hell', 'helplessly', 'hesitant', 'high-priced', 'hissed', 'hobble', 'hooligan', 'horrendous', 'horrified', 'hostage', 'hothead', 'hum', 'humming', 'hurting', 'hypocrisy', 'hysteria', 'idiocies', 'idiots', 'ignominy', 'ill-conceived', 'ill-formed', 'ill-treated', 'illegally', 'illogic', 'illusory', 'immaterial', 'immoderate', 'immorally', 'impatience', 'impede', 'imperfection', 'imperious', 'impetuous', 'implacable', 'implode', 'importune', 'impossible', 'impoverished', 'imprecision', 'improbably', 'imprudent', 'impulsive', 'inability', 'inaction', 'inadverent', 'inanely', 'inarticulate', 'incautious', 'incite', 'incoherence', 'incomparably', 'incompetent', 'incomprehension', 'inconsequent', 'inconsiderately', 'inconsolable', 'incorrect', 'incredulously', 'indecision', 'indelicate', 'indifferent', 'indignity', 'indiscriminate', 'indoctrination',
            'ineffectiveness', 'inefficacy', 'inelegant', 'ineptitude', 'inequitably', 'inevitable', 'inexorably', 'inexpiable', 'infamously', 'inferior', 'infidel', 'inflame', 'inflationary', 'infringement', 'infuriatingly', 'inhibition', 'inhumanity', 'injudicious', 'injustices', 'inordinately', 'insecure', 'insensitivity', 'insignificantly', 'insinuating', 'insolently', 'instigate', 'insubstantially', 'insufficiently', 'insultingly', 'insurmountably', 'interfere', 'interruption', 'intimidation', 'intractable', 'intrusive', 'invalidate', 'invidious', 'involuntary', 'irk', 'irksomely', 'ironically', 'irrationalities', 'irrecoverable', 'irredeemably', 'irrelevant', 'irresolvable', 'irreversible', 'irritated', 'isolated', 'itching', 'jam', 'jealousness', 'jeers', 'jitter', 'joke', 'judders', 'jutter', 'killer', 'knife', 'lack', 'lacking', 'lagged', 'lambast', 'lamentable', 'languorous', 'lapses', 'laughably', 'lawlessness', 'leakage', 'lech', 'leer', 'less-developed', 'lethargy', 'liable', 'licentiousness', 'life-threatening', 'limited', 'little-known', 'loathing', 'loneliness', 'long-winded', 'loose', 'losers', 'lost', 'lovelorn', 'lugubrious', 'lunaticism', 'lurking', 'maddening', 'madness', 'malcontent', 'malevolently', 'malign', 'mangled', 'maniacal', 'manipulators', 'martyrdom-seeking', 'mawkish', 'meanness', 'mediocrity', 'menace', 'menial', 'messes', 'militancy', 'misalign', 'misbecoming', 'miscalculation', 'misconception', 'miser', 'miserly', 'misgivings', 'mishap', 'misjudgment', 'mismanage', 'misreading', 'misses', 'mistakenly', 'mistrustful', 'misunderstandings', 'mock', 'mockingly', 'monotony', 'monstrously', 'morbidly', 'moronic', 'mortifying', 'mournful', 'mudslinging', 'murderer', 'mushy', 'mystify', 'naively', 'naughty', 'naïve', 'needy', 'negative', 'negligence', 'nervously', 'neurotically', 'nightmarishly', 'noisier', 'nonsense', 'noxious', 'objection', 'obliterated', 'obscenely', 'obscurity', 'obsolete', 'obstructed', 'obtuse', 'odd', 'oddly', 'offending', 'officious', 'one-sided', 'opponent', 'oppress', 'oppressors', 'outburst', 'outmoded', 'outrageousness', 'over-balanced', 'overacted', 'overbearingly', 'overemphasize', 'overpaid', 'overrated', 'oversights', 'overstate', 'overtaxed', 'overwhelm', 'overzealous', 'painfull', 'paltry', 'panders', 'panicky', 'paranoia', 'partiality', 'passiveness', 'pauper', 'pedantic', 'peevishly', 'perfunctory', 'pernicious', 'persecute', 'perturb', 'perversion', 'pessimism', 'petrified', 'phobic', 'pickets', 'pillory', 'pitiful', 'pity', 'plea', 'plotters', 'pointlessly', 'poky', 'polluters', 'poorest', 'powerless', 'precariously', 'prejudge', 'preoccupy', 'pretence', 'prevaricate', 'prickles', 'prisoner', 'procrastinates', 'prohibitive', 'prosecute', 'protracted', 'pugnacious', 'punishable', 'puppets', 'qualm', 'quarrellously', 'questionable', 'racism', 'radicalization', 'raging', 'ramshackle', 'ranted', 'raped', 'rattle', 'reactionary', 'recant', 'recklessness', 'refusal', 'refutation',
            'regress', 'regretful', 'regretted', 'rejects', 'reluctance', 'remorsefully', 'renunciation', 'reprehension', 'reprimand', 'repudiate', 'repugnantly', 'repulsively', 'resignation', 'restrict', 'retaliate', 'retards', 'revenge', 'reviled', 'revulsion', 'ricer', 'rife', 'rigidness', 'ripoff', 'rival', 'rollercoaster', 'rubbish', 'ruin', 'rumbling', 'run-down', 'rusty', 'ruts', 'sadden', 'sagging', 'sap', 'sardonically', 'savaged', 'scams', 'scandalously', 'scapegoat', 'scare', 'scarred', 'sceptical', 'scolding', 'scornful', 'scramble', 'scratch', 'screech', 'scuff', 'second-tier', 'seething', 'self-humiliation', 'selfish', 'sensationalize', 'servitude', 'severe', 'shady', 'shambles', 'shameless', 'shatter', 'shirk', 'shocked', 'shortage', 'shortsighted', 'shrill', 'shrug', 'sickening', 'sidetracked', 'simplistically', 'sinisterly', 'skeptical', 'skinny', 'slander', 'slap', 'slaves', 'slogging', 'sloow', 'slow', 'slowly', 'sluggish', 'slut', 'smash', 'smells', 'smolder', 'smudge', 'smugly', 'snag', 'snappishly', 'sneakily', 'snob', 'snub', 'sobering', 'sorely', 'sorry', 'spendy', 'spilling', 'spitefully', 'spoil', 'spoils', 'spooky', 'spotty', 'squabbling', 'squeaky', 'stab', 'stain', 'stalls', 'starkly', 'starve', 'steep', 'stereotypically', 'stiffness', 'stigmatize', 'stink', 'stooge', 'strain', 'stranger', 'stress', 'strict', 'strike', 'struggled', 'stubbornly', 'stumbled', 'stun', 'stupidity', 'stutter', 'stymied', 'subjugate', 'subpoenas', 'subversion', 'suck', 'sue', 'suffered', 'suffocate', 'suicide', 'sunk', 'superfluous', 'surrender', 'suspicious', 'swelled', 'symptom', 'taint', 'tangles', 'tardy', 'tattered', 'taut', 'tedious', 'temptation', 'tentatively', 'terribleness', 'terrorize', 'thankless', 'thoughtlessly', 'threatening', 'throbbing', 'thumbs-down', 'timidly', 'tired', 'toll', 'torrent', 'torturing', 'toughness', 'traduce', 'traitorous', 'transgression', 'trashed', 'traumatize', 'treacherously', 'tricked', 'trouble', 'troublesomely', 'tumbled', 'twist', 'tyrannical', 'uglier', 'ultimatum', 'unacceptable', 'unachievable', 'unavailable', 'unbelievably', 'unclean', 'uncomfy', 'unconstitutional', 'uncouth', 'undependable', 'underestimate', 'undermining', 'undetermined', 'undone', 'uneasy', 'uneven', 'unfairly', 'unfeeling', 'unfortunate', 'unfunded', 'unhappy', 'unimaginably', 'unintelligile', 'unjustified', 'unlamentable', 'unleash', 'unnatural', 'unnerved', 'unorthodox', 'unpredictable', 'unproved', 'unravel', 'unreasonable', 'unreliable', 'unsafe', 'unsecure', 'unsettlingly', 'unspeakablely', 'unsteady', 'unsure', 'unthinkable', 'untrustworthy', 'unuseably', 'unwarranted', 'unwilling', 'unworkable', 'uprising', 'uproarously', 'upsetting', 'usurper', 'vain', 'vengeance', 'venomous', 'vexation', 'vibrates', 'viciously', 'vilify', 'villianous', 'vindictiveness', 'violent', 'virulently', 'volatility', 'vulgar', 'wane', 'wariness', 'warped', 'wasteful', 'wayward', 'weakness', 'wedge', 'wheedle', 'whips', 'wickedness', 'wily',
            'wobbles', 'womanizer', 'worrier', 'worryingly', 'worthless', 'wrangle', 'wreck', 'wretchedly', 'wrip', 'wrongful', 'zapped', 'zombie']
    return neglist
